# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-14 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', '小型车'), ('1', '中型车'), ('2', '大型车')], default='0', max_length=2, verbose_name='车型')),
                ('carplate', models.CharField(max_length=30, verbose_name='车牌号')),
                ('inimg', models.ImageField(default='', upload_to='img/record', verbose_name='驶入图片')),
                ('outimg', models.ImageField(default='', upload_to='img/record', verbose_name='驶出图片')),
                ('in_time', models.DateTimeField(verbose_name='驶入时间')),
                ('out_time', models.DateTimeField(verbose_name='驶出时间')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='费用')),
            ],
            options={
                'verbose_name': '车辆类',
                'verbose_name_plural': '车辆类',
                'db_table': 'car',
            },
        ),
    ]
