# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-14 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carplate',
            field=models.CharField(max_length=100, verbose_name='车牌号'),
        ),
    ]
