# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paking', '0005_auto_20190416_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='outimg',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='驶出图片'),
        ),
    ]
