# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paking', '0006_auto_20190416_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='驶出时间'),
        ),
    ]
