# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-14 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartype', models.CharField(choices=[('0', '小型车'), ('1', '中型车'), ('2', '大型车')], default='0', max_length=2, verbose_name='车型')),
                ('feestand', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='收费标准')),
                ('start_time', models.TimeField(verbose_name='起始时间')),
                ('end_time', models.TimeField(verbose_name='终止时间')),
                ('picture', models.ImageField(upload_to='img/type', verbose_name='车型图片')),
                ('text', models.TextField(verbose_name='车型介绍')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'verbose_name': '收费标准',
                'verbose_name_plural': '收费标准',
                'db_table': 'standard',
            },
        ),
    ]
