# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-14 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0002_standard_time_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='text',
        ),
    ]
