# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0003_auto_20190314_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='feestand',
        ),
        migrations.AddField(
            model_name='standard',
            name='all_day_money',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='全天价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='day_money',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='白天价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='night_money',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='夜间价格'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standard',
            name='end_time',
            field=models.TimeField(verbose_name='白天结束计费节点'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='start_time',
            field=models.TimeField(verbose_name='白天开始计费节点'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='time_unit',
            field=models.CharField(choices=[('0', '15分钟'), ('1', '30分钟'), ('2', '每小时'), ('3', '每天'), ('4', '每周'), ('5', '每月')], max_length=20, verbose_name='时间单位'),
        ),
    ]
