# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-15 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0004_auto_20190315_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='time_unit',
        ),
    ]
