# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-15 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0005_remove_standard_time_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='time_unit',
            field=models.CharField(choices=[('0', '15分钟'), ('1', '30分钟'), ('2', '每小时'), ('3', '每天'), ('4', '每周'), ('5', '每月')], default=1, max_length=20, verbose_name='时间单位'),
            preserve_default=False,
        ),
    ]
